# Permalinks
permalink:            pretty
relative_permalinks:  true

# Plugins
#gems: [jekyll-sitemap, sass, jekyll-remote-plantuml]

# Setup
title:                Patouche
paginate:             5
baseurl:              /
markdown:             kramdown
highlighter:          pygments

includes: [_post/java,_post/linux,_post/others]

# Blog section
blog:
    name:             "// happy coding"

    # Author section
author:
    name:             Patouche

# Remote PlantUML
plantuml:
    binaries:         assets/images/plantuml/
    type:             png
    encode:           encode64
    url:              http://www.plantuml.com/plantuml/{type}/{code}

# Sass support
sass:
    sass_dir:         _sass
    style:            :compressed
