# Permalinks
permalink:            pretty
relative_permalinks:  true
#safe:                 false
#lsi:                  false

# Plugins
gems: [jekyll-sitemap, sass,rouge]

# Setup
title:                Patouche
paginate:             5
baseurl:              /
markdown:             kramdown
highlighter:          pygments

includes: [_post/java,_post/linux,_post/others,images]

# Blog section
blog:
    name:             "// happy coding"

# Author section
author:
    name:             Patouche

# Remote PlantUML
plantuml:
    assets:           images/plantuml-images/
    type:             png
    encode:           encode64
    url:              http://www.plantuml.com/plantuml/{type}/{code}

# Sass support
sass:
    sass_dir:         _sass
    style:            :compressed
