# Permalinks
permalink:            pretty
relative_permalinks:  true

# Setup
title:                Patouche
paginate:             5
baseurl:              /
markdown:             kramdown
highlighter:          pygments

includes: [_post/java,_post/linux,_post/others]

# Blog section
blog:
    name:             "// happy coding"

# Author section
author:
    name:             Patouche

# Sass support
sass:
    sass_dir:         _sass
    style:            :compressed
